### ISSUE TITLE
body of a received message should not be editable

### ISSUE THREAD

**Issue by fluxionary** [minetest-mail/mail_mod#15]
Opening this on behalf of another person.

The contents of a mail that you are reading, should not be in an editable textarea, this can lead to someone typing a reply in the message they are reading, and not being able to send it. 

I think this can be fixed by changing [this line](https://github.com/minetest-mail/mail_mod/blob/461f57cde892930a08330bae1b41f8e6c5f9d2b1/gui.lua#L261) to

```
			textarea[0.25,1.8;8,7.8;;;%s]
```

**Comment by BuckarooBanzay** [comment]
fixed, thanks :+1:
